### ISSUE TITLE
Use mailgun open tracking instead of Ahoy

### ISSUE THREAD

**Issue by tdooner** [openoakland/disclosure-alert#79]
Open tracking is key to understanding whether we should continue sending to a user. Since it's removed from Ahoy 2, let's reimplement via Mailgun.

- [x] Add new model to replace Ahoy
- [x] Let it run for a while
- [x] Backfill old data
- [ ] Update admin metrics to use new table
- [ ] Remove Ahoy

**Comment by tdooner** [comment]
Blocks #62
